### PR TITLE
added tracking for new user

### PR DESCRIPTION
**Pull request by chitalian**

### CODE REVIEW

**Comment by calum-bird** [comment]
For some reason mixpanel isn't tracking login events. Wondering if we need to use a different event name for some reason? Has no problem tracking generations/favourites.

**Comment by chitalian** [comment]
> For some reason mixpanel isn't tracking login events. Wondering if we need to use a different event name for some reason? Has no problem tracking generations/favourites.

It seems like it is working for me
@calum-bird 
image

**Comment by chitalian** [comment]
It works! I favorited five Dog ones and 
image
and then did a random dog one and it worked!
image

**Comment by calum-bird** [comment]
I'm just gonna merge as I couldn't reproduce and logins are now tracking for me.

**Pull request merged**
